on:
  push:

  release:
    types:
      - published

jobs:
  create-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: sinofseven/action-request-id-token@v1.0.0
        id: get-token
        with:
          audience: test
      - run: echo "$TOKEN" > jwt.txt
        env:
          TOKEN: ${{ steps.get-token.outputs.jwt-token }}
      - name: Upload JWT artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: jwt
          path: jwt.txt
