on:
  push:

  release:
    types:
      - published

jobs:
  create-jwt:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: sinofseven/action-request-id-token@v1.0.0
        id: get-token
        with:
          audience: test
      - uses: actions/create-github-app-token@v3
        id: get-pat
        with:
          client-id: Iv23livz86i46FXV6gNa
          private-key: ${{ secrets.PRIVATE_KEY_LUCIFEROUS_TAP_PAT_PROVIDER }}
          owner: sinofseven
          repositories: workflow-call-test-function
      - uses: sinofseven/action-repository-dispatch@v1.0.0
        with:
          target_repo: sinofseven/workflow-call-test-function
          event_type: update
          token: ${{ steps.get-pat.outputs.token }}
          payload: '{"jwt": "${{ steps.get-token.outputs.jwt-token }}"}'
